# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='asdasdasd',
            field=models.FloatField(default=0, verbose_name='sdfsdfsdf'),
        ),
    ]
