# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0003_remove_ingredient_asdasdasd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='preparation',
        ),
    ]
