# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20161008_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='course',
        ),
    ]
