# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20161010_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportedrecipe',
            name='id',
        ),
        migrations.AlterField(
            model_name='reportedrecipe',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recipe.Recipe'),
        ),
    ]
