# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_remove_recipe_course'),
        ('recipe_groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='author',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
